import { StyleSheet } from "react-native";

export default StyleSheet.create({
	container: {
		flex: 1,
		alignItems: 'center',
		overflow: 'hidden',
		width: '100%',
		height: '100%',
		backgroundColor: '#DBF6FF',
		backgroundSize: '100vh',
	},
	form: {
		display: 'flex',
		alignItems: 'center',
		flexDirection: 'column',
		marginLeft: 20,
		textAlign: 'center',
	},
	backgroundImage: {
		backgroundImage: 'url("./assets/downwaves1.svg"), url("./assets/upwaves1.svg")',
		backgroundRepeat: 'no-repeat, no-repeat',
		backgroundSize: '100vw, 100vw',
		backgroundPosition: 'bottom, top',
	},
	logo: {
		width: 150,
		height: 100,
		marginTop: 50,
		marginLeft: 130,
		marginBottom: 30,
	},
	reserveButton: {
		appearance: 'none',
		padding: 10,
		borderWidth: 0,
		backgroundColor: '#0099FF',
		fontWeight: '700',
		fontSize: 'large',
		color: '#fff',
		borderRadius: 10,
		width: '50vw',
		height: 56,
		fontFamily: 'Kanit',
		margin: 20,
	},
	placesInput: {
		width: 220,
		height: 40,
		marginTop: 15,
		marginBottom: 30,
		fontFamily: 'Kanit',
		fontSize: 'smaller',
		borderWidth: 0,
		borderRadius: 10,
		color: '#000',
		backgroundColor: '#fff',
		padding: 10,
		appearance: 'none',
		fontWeight: '700',
	},
	freespotsText: {
		marginTop: 15,
		fontFamily: 'Kanit',
		fontSize: 32,
		fontWeight: '700',
		lineHeight: 48,
		letterSpacing: 0,
	},
	nospotsText: {
		marginBottom: 10,
		marginRight: 20,
	},
	timeText: {
		fontFamily: 'Kanit',
		fontSize: 32,
		fontWeight: '700',
		lineHeight: 48,
		letterSpacing: 0,
		textAlign: 'center',
		marginTop: 10,
	},
	star: {
		margin: 0,
		padding: 0,
		boxSizing: 'border-box',
		textDecoration: 'none',
	},
	htmlBody: {
		fontFamily: 'Kanit, sans-serif',
	},
});